<div class="weixinitem weixinitem_mid">
<div class="weixinitempic">
<a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="280"></a>
</div>
<div class="weixinbody">
<div class="time">
[field:pubdate function="MyDate('Y.m.d',@me)"/]<b>.</b>
</div>
<div class="weixintit"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
<div class="weixinb">
[field:infos/]...
<br><a href="[field:arcurl/]" target="_blank">阅读全文</a>
</div>
</div>
</div>