<li>
  <a target="_blank" href="[field:arcurl/]">
  <div class="case_list_body_pic">
      <img src="[field:litpic/]" height="146" width="216">
  </div>
  <div class="case_list_info">
      <p class="cast_list_tit">[field:title/]</p>
      <p class="cast_list_kaifa">开发语言：<br>php + MsSql</p>
      <p>
          </p><div style="margin-top: 0px;" class="case_open"></div>
      <p></p>
  </div>
  </a>
</li>