<div class="news_list_li">
<div class="news_list_li_pic" style="display:none"><img src="" width="100%"></div>
<div class="index_news_addtime en news_list_li_addtime">[field:pubdate function="MyDate('Y.m.d',@me)"/]<b>.</b></div>
<div class="index_news_tit"><a target="_blank" href="[field:arcurl/]">[field:title/]</a></div>
<div class="index_news_info news_list_li_info">[field:description function="cn_substr(Html2text(@me),300)"/]...</div>
<div class="news_list_li_more"><a href="[field:arcurl/]">Read more</a></div>
</div>