<?php
$z[0]=Array("arcurl","",37,52);
$z[1]=Array("title","",64,78);
$z[2]=Array("title","",87,101);
$z[3]=Array("litpic","",108,123);
$z[4]=Array("arcurl","",179,194);
$z[5]=Array("title","",196,210);
$z[6]=Array("description","",224,285);
$z[6][4]['function']="cn_substr(Html2text(@me),300)";
$z[7]=Array("pubdate","",324,370);
$z[7][4]['function']="GetDateTimeMK(@me)";
$z[8]=Array("click","",390,404);

?>