<?php
$z[0]=Array("type","<li><a href=\"[field:typeurl/]\">Service<b>.</b><span>服务</span></a></li>",113,221);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<li><a href=\"[field:typeurl/]\">Html5<b>.</b><span>案例</span></a></li>",223,329);
$z[1][4]['typeid']="4";
$z[2]=Array("type","<li><a href=\"[field:typeurl/]\">wap<b>.</b><span>手机</span></a></li>",331,436);
$z[2][4]['typeid']="11";
$z[3]=Array("type","<li><a href=\"[field:typeurl/]\">About<b>.</b><span>关于</span></a></li>",438,545);
$z[3][4]['typeid']="16";
$z[4]=Array("type","<li><a href=\"[field:typeurl/]\">News<b>.</b><span>资讯</span></a></li>",547,653);
$z[4][4]['typeid']="22";
$z[5]=Array("type","<li><a href=\"[field:typeurl/]\" id=\"tt\">Contact<b>.</b><span>联系</span></a></li>",655,772);
$z[5][4]['typeid']="25";

?>