<?php
$z[0]=Array("global","",170,196);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",240,270);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",307,334);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",669,691);
$z[3][4]['name']="typename";
$z[4]=Array("include","",946,981);
$z[4][4]['filename']="kefu.htm";
$z[5]=Array("include","",983,1020);
$z[5][4]['filename']="header.htm";
$z[6]=Array("channel"," \r\n <a href='[field:typelink/]'><font>[field:typename/]</font></a>\r\n",1233,1355);
$z[6][4]['typeid']="34";
$z[6][4]['type']="son";
$z[7]=Array("field","",1464,1486);
$z[7][4]['name']="typename";
$z[8]=Array("field","",1500,1521);
$z[8][4]['name']="content";
$z[9]=Array("include","",1603,1640);
$z[9][4]['filename']="footer.htm";

?>