<?php
$z[0]=Array("global","",170,196);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",240,270);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",307,334);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",599,634);
$z[3][4]['filename']="kefu.htm";
$z[4]=Array("include","",636,673);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",7482,7519);
$z[5][4]['filename']="footer.htm";

?>