<?php
$z[0]=Array("global","",170,196);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",240,270);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",307,334);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",660,682);
$z[3][4]['name']="typename";
$z[4]=Array("include","",919,954);
$z[4][4]['filename']="kefu.htm";
$z[5]=Array("include","",956,993);
$z[5][4]['filename']="header.htm";
$z[6]=Array("type","<a href=\"[field:typelink/]\" class=\"hov\" title=\"全部新闻\"><font>全部资讯</font></a>",1179,1303);
$z[6][4]['typeid']="4";
$z[7]=Array("channel"," \r\n <a href='[field:typelink/]'><font>[field:typename/]</font></a>\r\n",1313,1435);
$z[7][4]['typeid']="22";
$z[7][4]['type']="son";
$z[8]=Array("list","\r\n<dl class=\"new_list2\">\r\n<dt><a href=\"[field:arcurl/]\"><img alt=\"[field:title/]\" title=\"[field:title/]\" src=\"[field:litpic/]\" height=\"92\" width=\"149\"></a></dt>\r\n<dd>\r\n<h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n<p>[field:description function=\"cn_substr(Html2text(@me),300)\"/]...</p>\r\n<div><ul class=\"new_info\"><li>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</li><li class=\"ll\">[field:click/]</li></ul></div>\r\n</dd>\r\n</dl>\r\n",1493,1968);
$z[8][4]['pagesize']="10";
$z[9]=Array("pagelist","",2064,2142);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2468,2505);
$z[10][4]['filename']="footer.htm";

?>