<?php
$z[0]=Array("global","",170,196);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",240,270);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",307,334);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",664,686);
$z[3][4]['name']="typename";
$z[4]=Array("include","",941,976);
$z[4][4]['filename']="kefu.htm";
$z[5]=Array("include","",978,1015);
$z[5][4]['filename']="header.htm";
$z[6]=Array("type","<a href=\"[field:typelink/]\" class=\"hov\" title=\"全部案例\"><font>全部作品</font></a>",1203,1327);
$z[6][4]['typeid']="4";
$z[7]=Array("channel"," \r\n <a href='[field:typelink/]'><font>[field:typename/]</font></a>\r\n",1337,1458);
$z[7][4]['typeid']="4";
$z[7][4]['type']="son";
$z[8]=Array("list","\r\n<li>\r\n  <a target=\"_blank\" href=\"[field:arcurl/]\">\r\n  <div class=\"case_list_body_pic\">\r\n      <img src=\"[field:litpic/]\" height=\"146\" width=\"216\">\r\n  </div>\r\n  <div class=\"case_list_info\">\r\n      <p class=\"cast_list_tit\">[field:title/]</p>\r\n      <p class=\"cast_list_kaifa\">开发语言：<br>php + MsSql</p>\r\n      <p>\r\n          </p><div style=\"margin-top: 0px;\" class=\"case_open\"></div>\r\n      <p></p>\r\n  </div>\r\n  </a>\r\n</li>\r\n",1504,1975);
$z[8][4]['pagesize']="100";
$z[9]=Array("include","",4415,4452);
$z[9][4]['filename']="footer.htm";

?>